import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { AppTitle } from '@/utils/constants'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export async function generateMetadata({ params }) {
  return {
    title: AppTitle,
    description: 'Generated by create next app',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
